### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by madeleinevironda** [twomice/com.joineryhq.reltoken#10]
We would like to use this extension and were wondering whether you were planning on tagging a release version? Thank you

**Comment by twomice** [comment]
Thank you for the nudge; I've tagged v0.2 now, so civicrm.org should list that as a release version within 24 hours at https://civicrm.org/extensions/related-tokens

Please note, there would be another step still before this would be available for in-app installation, so even with this tagged release, to use this on your site you will still need to follow the steps for "Manual installation of native extensions" at https://docs.civicrm.org/sysadmin/en/latest/customize/extensions/#installing-a-new-extension.

**Comment by madeleinevironda** [comment]
Great, thank you!
