### ISSUE TITLE
Default values aren't generated on install

### ISSUE THREAD

**Issue by MegaphoneJon** [twomice/com.joineryhq.reltoken#7]
In your comments on #5 you asked me to to default the value of "generate tokens for this relationship" to "yes", which I did.  However, that doesn't actually generate records in the custom value table; you need to edit and save a relationship for the change to take effect.  I'm not sure how to fix that but I thought I'd report the bug I created :)

**Comment by twomice** [comment]
Thanks for reporting this @MegaphoneJon I don't entirely understand the issue; could I ask you to restate it in a "do this, then observe that" style?

**Comment by MegaphoneJon** [comment]
Sure!
* Install reltoken on a site where it hasn't been installed before.
* Try to use the tokens, or find them in the token drop-down.  Observe they're not there.
* Go to **Administer » Customize Data and Screens » Relationship Types**.
* Click **View** next to a relationship type.  Note that *Generate tokens for this relationship type* is set to *Yes* - even though the tokens aren't generated.
* Click **Edit** next to a relationship type, then click **Save**.
* Observe how the tokens are now generated for that relationship type.

**Comment by MegaphoneJon** [comment]
I realized how to handle this.  On install (or maybe post-install - not sure if install hook runs before or after `hook_civicrm_managed`) one should do an API query for all existing RelationshipType records and update them by setting the new custom field to `1`.

**Comment by twomice** [comment]
Attention @lucky091588.

**Comment by twomice** [comment]
Fixed in PR #16.
